# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.0"

gem "activeadmin", "= 2.13.1"
gem 'active_admin_theme'
gem "devise", "= 4.9.2"
gem "dotenv-rails", "= 2.8.1"
gem "draper", "= 4.0.2"
gem "jsonb_accessor", "= 1.3.10"
gem "memery", "= 1.4.1"
gem "puma", "~> 5.0"
gem "rails", "~> 7.0.4", ">= 7.0.4.3"
gem "sassc"
gem "slim", "= 5.1.1"
gem "sprockets-rails"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

gem "annotate", "= 3.2.0"
gem 'aws-sdk-s3', "~> 1"
gem "docker-api", "~> 1.22.0"
gem "enumerize", "= 2.6.1"
gem "git", "= 1.18.0"
gem "httparty", "= 0.21.0"
gem "pg", "= 1.5.3"
gem "sidekiq", "= 7.0.9"

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "rubocop"
  gem "rubocop-rails"
end

group :development do
  gem "pry"
  gem "spring"
end

group :test do
  gem "rubocop-rspec", require: false
  %w[rspec-core rspec-expectations rspec-mocks rspec-rails rspec-support].each do |lib|
    gem lib, git: "https://github.com/rspec/#{lib}.git", branch: "main"
  end
end
