# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.3.0"

gem "aasm", "~> 5.5.0"
gem "activeadmin", "~> 3.2.0"
gem "active_admin_theme"
gem "annotate", "~> 3"
gem "aws-sdk-s3", "~> 1"
gem "brakeman"
gem "csv"
gem "devise", "~> 4.9.0"
gem "docker-api", "~> 2.2.0"
gem "draper", "~> 4.0"
gem "enumerize", "~> 2.7"
gem "git", "~> 1.19"
gem "health-monitor-rails"
gem "httparty", "~> 0.21"
gem "jsonb_accessor", "~> 1.4"
gem "memery", "~> 1.5"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "rails", "~> 7.1.0"
gem "redis-client"
gem "rswag-api"
gem "rswag-ui"
gem "sassc"
gem "service_actor", "~> 3.7"
gem "sidekiq", "~> 7.2"
gem "slim", "~> 5.2.0"
gem "sprockets-rails"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
gem "with_advisory_lock"

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "rswag-specs"
  gem "rubocop"
  gem "rubocop-factory_bot", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rake", require: false
  gem "rubocop-rspec", require: false
  gem "rubocop-thread_safety", require: false
end

group :development do
  gem "annotaterb"
  gem "bundler-audit"
  gem "database_consistency", require: false
  gem "pry"
  gem "spring"
end

group :test do
  gem "rspec-its"
  gem "rspec-rails"

  gem "factory_bot", "~> 6"
  gem "faker", "~> 3.2.0"
  gem "shoulda-matchers", "~> 6.1"
  gem "simplecov", require: false
end
